fix(py36): Drop Python 3.6 and add 3.11 support
Python 3.6 support hasn't actually worked since the use of `dataclasses`:

    $ ./.tox/py36/bin/sphinx-watch --help
    Traceback (most recent call last):
      File "./.tox/py36/bin/sphinx-watch", line 7, in <module>
        from sphinx_watch.cli import main
      File "/home/rpatterson/src/devel/sphinx-watch/.tox/py36/lib/python3.6/site-packages/sphinx_watch/cli.py", line 9, in <module>
        from .handlers import SphinxSourceEventHandler
      File "/home/rpatterson/src/devel/sphinx-watch/.tox/py36/lib/python3.6/site-packages/sphinx_watch/handlers.py", line 4, in <module>
        from dataclasses import dataclass
    ModuleNotFoundError: No module named 'dataclasses'

These supported versions are better anyways because they correspond to the currently
supported Python versions.