fix(py37): Restore broken Python 3.7 support
Addresses this error:

    py37: commands[0]> sphinx-watch --help
    Traceback (most recent call last):
      File "/home/rpatterson/src/devel/sphinx-watch/.tox/py37/bin/sphinx-watch", line 5, in <module>
	from sphinx_watch.cli import main
      File "<fstring>", line 1
	(source_dir=)
		   ^
    SyntaxError: invalid syntax
    py37: exit 1 (0.02 seconds) /home/rpatterson/src/devel/sphinx-watch> sphinx-watch --help pid=1698868

This also improves the output which previously was printing `repr()` strings instead of
just the path.  Before:

    build: commands[0]> sphinx-watch ./docs/ ./build/docs/html/ html --httpd
    sphinx-watch version is 0.1.2
    Sphinx version is 5.3.0
    Env is:
	    source_dir=PosixPath('/home/rpatterson/src/devel/sphinx-watch/doc')
	    build_dir=PosixPath('/home/rpatterson/src/devel/sphinx-watch/build')
	    builder='html'

After:

    py37: commands[0]> sphinx-watch ./doc/ ./build/ html
    sphinx-watch version is 0.1.2
    Sphinx version is 5.3.0
    Env is:
	   source_dir=/home/rpatterson/src/devel/sphinx-watch/doc
	   build_dir=/home/rpatterson/src/devel/sphinx-watch/build
	   builder=html